downloads vert.x and openjdk 7

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,132 +1,64 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# Parse args
+# fail fast
+set -e
+
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
+# parse args
 BUILD_DIR=$1
 CACHE_DIR=$2
 
-PLAY_PATH=".play"
-IVY_PATH=".ivy2"
+#create the cache dir if it doesn't exist
+mkdir -p $CACHE_DIR
 
-# Change dir to handle relative paths
 cd $BUILD_DIR
-
-# Unpack cache
-for DIR in $PLAY_PATH $IVY_PATH ; do
-  rm -rf $DIR
-  if [ -d $CACHE_DIR/$DIR ]; then
-    cp -r $CACHE_DIR/$DIR $DIR
-  fi
-done
-
-check_compile_status()
-{
-  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-    echo " !     Failed to build Play! application"
-    rm -rf $CACHE_DIR/$PLAY_PATH
-    echo " !     Cleared Play! framework from cache"
-    exit 1
-  fi
-}
-
-install_play()
-{
-  VER_TO_INSTALL=$1
-  PLAY_URL="https://s3.amazonaws.com/heroku-jvm-langpack-play/play-heroku-$VER_TO_INSTALL.tar.gz"
-  PLAY_TAR_FILE="play-heroku.tar.gz"
-  echo "-----> Installing Play! $VER_TO_INSTALL....."
-  curl --silent --max-time 150 --location $PLAY_URL -o $PLAY_TAR_FILE
-  if [ ! -f $PLAY_TAR_FILE ]; then
-    echo "-----> Error downloading Play! framework. Please try again..."
-    exit 1
-  fi
-  if [ -z "`file $PLAY_TAR_FILE | grep gzip`" ]; then
-    echo "-----> Error installing Play! framework or unsupported Play! framework version specified. Please review Dev Center for a list of supported versions."
-    exit 1
-  fi
-  tar xzf $PLAY_TAR_FILE
-  rm $PLAY_TAR_FILE
-  chmod +x $PLAY_PATH/play
-  echo "-----> done"
-}
-
-PLAY_VERSION=`grep 'play[ \t]*[0-9\.]' conf/dependencies.yml | sed -E -e 's/[ \t]*-[ \t]*play[ \t]*([1-9\.]*).*/\1/'`
-DEFAULT_PLAY_VERSION="1.2.4"
-VERSION_DECLARED=true
-
-if [ -z "$PLAY_VERSION" ] ; then
-  PLAY_VERSION=$DEFAULT_PLAY_VERSION
-  VERSION_DECLARED=false
-  echo "-----> WARNING: Play! version not specified in dependencies.yml. Default version: $PLAY_VERSION being used...."
+if [ -d "$CACHE_DIR/.jdk7" ]; then
+  echo -n "copying jdk to app"
+  cp -r "$CACHE_DIR/.jdk7" $BUILD_DIR
+  echo "done"
 fi
-
-# Install Play! or update the version
-if [ ! -d $PLAY_PATH ]; then
-  install_play $PLAY_VERSION
-else
-  INSTALLED_PLAY_VERSION=`cat $PLAY_PATH/framework/src/play/version`
-  if [ "$INSTALLED_PLAY_VERSION" != "$PLAY_VERSION" ] && $VERSION_DECLARED ; then
-    echo "-----> Updating Play! version. Previous version was $INSTALLED_PLAY_VERSION. Updating to $PLAY_VERSION..."
-    rm -rf $PLAY_PATH
-    install_play $PLAY_VERSION
-  fi
-fi
-
-PLAY_SETTINGS_URL="http://s3.amazonaws.com/heroku-jvm-langpack-play/ivysettings.xml"
-
-echo -n "-----> Installing ivysettings.xml....."
-if [ -f .ivy2/ivysettings.xml ]; then
-  rm .ivy2/ivysettings.xml 
-fi
-curl --silent --max-time 10 --location $PLAY_SETTINGS_URL --create-dirs --output .ivy2/ivysettings.xml
-echo " done"
 
 OPENJDK7_URL="https://s3.amazonaws.com/heroku-jvm-langpack-java/openjdk7-u2-heroku-temaki.tar.gz"
 
 if [ ! -d "$BUILD_DIR/.jdk7" ]; then
-     echo -n "-----> Installing OpenJDK7u2 build (to .jdk7)....."
-     mkdir "$BUILD_DIR/.jdk7"
-     cd "$BUILD_DIR/.jdk7"
-     curl --silent --max-time 180 --location $OPENJDK7_URL | tar xz
-     echo " done"
-fi 
+  echo -n "-----> Installing OpenJDK7u2 build (to .jdk7)....."
+  mkdir "$BUILD_DIR/.jdk7"
+  cd "$BUILD_DIR/.jdk7"
+  curl --silent --max-time 180 --location $OPENJDK7_URL | tar xz
+  echo " done"
+fi
 
-cd "$BUILD_DIR"
 export JAVA_HOME="$BUILD_DIR/.jdk7"
-export PATH="$BUILD_DIR/.jdk7/bin:$PATH"
 
-# Build app
-echo "-----> Building Play! application..."
-$PLAY_PATH/play version | sed -u 's/^/       /'
+cp -r .jdk7 $CACHE_DIR/.jdk7
 
-# Precompile the Play! application at the root of $BUILD_DIR
-APP_DIR=./
-echo "       Building Play! application at directory $APP_DIR"
+cd $BUILD_DIR
+if [ -d "$CACHE_DIR/.vertx" ]; then
+  echo -n "copying vertx to app"
+  cp -r "$CACHE_DIR/.vertx" $BUILD_DIR
+  echo "done"
+fi
 
-DEPENDENCIES_CMD="$PLAY_PATH/play dependencies $APP_DIR --forceCopy --silent -Duser.home=$BUILD_DIR 2>&1"
-echo "       Resolving dependencies: $DEPENDENCIES_CMD"
-eval "$DEPENDENCIES_CMD" | sed -u 's/^/       /'
-check_compile_status
+VERTX_URL ="https://github.com/downloads/purplefox/vert.x/vert.x-1.0.beta10.tar.gz"
 
-PRECOMPILE_CMD="$PLAY_PATH/play precompile $APP_DIR --silent 2>&1"
-echo "       Precompiling: $PRECOMPILE_CMD" 
-eval "$PRECOMPILE_CMD" | sed -u 's/^/       /'
-check_compile_status
+if [ ! -d "$BUILD_DIR/.vertx" ]; then
+  echo -n "-----> Installing Vert.x build (to .vertx)....."
+  mkdir "$BUILD_DIR/.vertx"
+  cd "$BUILD_DIR/.vertx"
+  curl --silent --max-time 320 --location $VERTX_URL | tar xz
+  chmod +x bin/vertx
+  echo " done"
+fi
 
-# Repack Play! framework into cache
-mkdir -p $CACHE_DIR
-for DIR in $PLAY_PATH $IVY_PATH ; do
-  rm -rf $CACHE_DIR/$DIR
-  cp -r $DIR $CACHE_DIR/$DIR
-done
+export JAVA_HOME="$BUILD_DIR/.jdk7"
 
-# Remove build time dependencies from slug
-# (Note: runtime modules are copied to slug with --forceCopy option)
-rm -fr $PLAY_PATH/modules
-rm -fr $IVY_PATH
+cp -r .jdk7 $CACHE_DIR/.jdk7
+cp -r .vertx $CACHE_DIR/.vertx
+
 
 # Warn if no Procfile is present
 if [ ! -f Procfile ]; then
   echo "-----> No Procfile found. Will use the following default process: "
-  echo "       play run --http.port=\$PORT \$PLAY_OPTS"
+  echo "       vertx run server.js"
 fi
